/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
extern void led_blink(void);

int main(void)
{
    led_blink();

    while(1);
}
*/

/*
#include "button_press.h"

int main(void)
{
    button_press();

    while(1);
}

*/
/*
#include "alternate_led_blink.h"

int main(void)
{
    alternate_led_blink();

    while(1);
}
*/


#include "button_press.h"
#include "alternate_led_blink.h"

#include "delay.h"
int main(void)
{
    button_press_init();
    alternate_led_init();

    while(1)
    {
        button_press_task();
        alternate_led_task();
        delay(1000);           // Small delay
    }
}
