name: C Programs CI

on:
  push:
    branches: ["main"]
    paths:
      - "c-codes/**"
  pull_request:
    branches: ["main"]
    paths:
      - "c-codes/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile and Run C Programs
      run: |
        set -e

        echo "Searching for C files in c-codes..."

        files=$(find c-codes -name "*.c")

        echo "Files found:"
        echo "$files"
        echo "--------------------------------"

        for file in $files
        do
          exe="/tmp/$(basename "$file" .c)"

          echo "Compiling $file -> $exe"

          gcc -Wall -Wextra -fsanitize=address -g "$file" -o "$exe"

          echo "Running $exe"

          # Provide input for array programs
          if [[ "$file" == *"array.c"* ]]; then
            echo -e "5\n1 2 3 4 5" | "$exe"
          else
            timeout 2s "$exe" || echo "Program finished or required input"
          fi

          echo "SUCCESS: $file compiled and executed"
          echo "--------------------------------"
        done
